// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvY2bAV1RYdP5xuDIkUQTtZdrzDgQAKO0',
    appId: '1:292507911533:android:e7c4b807f875245bc38664',
    messagingSenderId: '292507911533',
    projectId: 'stationery-hub-4b34e',
    storageBucket: 'stationery-hub-4b34e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNVcgT0yt6Wst7RIJth86VWGxXVQWbHpY',
    appId: '1:292507911533:ios:eafd48b20195a196c38664',
    messagingSenderId: '292507911533',
    projectId: 'stationery-hub-4b34e',
    storageBucket: 'stationery-hub-4b34e.appspot.com',
    androidClientId:
        '292507911533-g0hccg36j9nsehcbfe5noeo64gcrd2dl.apps.googleusercontent.com',
    iosClientId:
        '292507911533-1oc4a50uaa1851nt3e5p8dihjpqvrf5d.apps.googleusercontent.com',
    iosBundleId: 'com.flyingantsstudios.stationeryhubAttendance',
  );
}
